### ISSUE TITLE
SUGGESTION: option to decide position of the window

### ISSUE THREAD

**Issue by BeyondMagic** [LoupLobet/91menu#3]
It would be nice to put in certain positions with an option like:

```Rust
       -p +x+y
       -p -x-y
       -p -x+y
       -p +x-y
```

I want to say, too, that this is really awesome and very lightweight, my 2006 computer appreciates your code :)

**Comment by LoupLobet** [comment]
Yes It's a pretty good idea, I do this as soon as possible ! Thanks for your encouragements !

**Comment by LoupLobet** [comment]
It's done, you can now specify a geometry for the menu with the -g option or the config.h file !
The format is the XParseGeometry(3) format: [=][<width>{xX}<height>][{+-}<xoffset>{+-}<yoffset>] (the man page is up to date).
Please let me know if you have any other problem :)

PS: the old -g option (to grab mouse buttons) is now -m

**Comment by BeyondMagic** [comment]
Thanks.

**Comment by BeyondMagic** [comment]
It would be fun if either the `<width>` and `<height>` are set to 0, it'd uses the minimum width/height of the window. You don't have to do that, though, I think the option by itself already does a lot.

**Comment by LoupLobet** [comment]
If I do that it gona break the XParseGeometry(3) format and convention. But
if you really want this (because maybe you really want that)m I can do a
patch ?

Le dim. 16 mai 2021 à 19:33, BeyondMagic ***@***.***> a
écrit :

**Comment by BeyondMagic** [comment]
I"m trying to write it myself and failing to do so, but create the patch only if you have free time. Thanks for the fast response.

Tried parsing the `geometry` string to get each number, and verify the `w` and `h` and then later replace on the `XParseGeometry`.

**Comment by LoupLobet** [comment]
I just made a new commit where the width and the height are ignored (in the
geometry) if they aren't both greater than the minimal width/height. I
think It can do the trick (You will have minimal with/height with 0, and it
avoid inconsitent geometry).

Le dim. 16 mai 2021 à 19:52, BeyondMagic ***@***.***> a
écrit :

**Comment by BeyondMagic** [comment]
Thanks! Will give a look.

**Comment by BeyondMagic** [comment]
Works perfectly.

**Comment by LoupLobet** [comment]
Nice ! Don't hesitate if you have other suggestions :)

Le dim. 16 mai 2021 à 20:01, BeyondMagic ***@***.***> a
écrit :
